package main

import "strings"

func LoremIpsum(paragraphs int) string {
	return strings.Join(strings.Split(loremIpsum, "\n")[:paragraphs], "\n\n")
}

var loremIpsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eget nunc lobortis mattis aliquam faucibus purus in massa. Elit eget gravida cum sociis natoque penatibus et magnis. Ipsum dolor sit amet consectetur. Est ante in nibh mauris cursus mattis molestie a iaculis. Neque volutpat ac tincidunt vitae. Convallis tellus id interdum velit. Arcu risus quis varius quam quisque id diam vel quam. A cras semper auctor neque vitae. Egestas tellus rutrum tellus pellentesque eu. In mollis nunc sed id semper risus in hendrerit. Ipsum a arcu cursus vitae congue mauris rhoncus aenean vel. Fames ac turpis egestas maecenas pharetra. Gravida rutrum quisque non tellus orci ac auctor augue. Mi proin sed libero enim sed faucibus turpis in eu. Consectetur libero id faucibus nisl tincidunt eget. Tristique senectus et netus et malesuada fames.
Hendrerit dolor magna eget est lorem ipsum. Massa tincidunt nunc pulvinar sapien. Suspendisse in est ante in nibh mauris cursus mattis. Gravida arcu ac tortor dignissim convallis aenean et tortor. Tortor dignissim convallis aenean et tortor at risus viverra. Facilisi etiam dignissim diam quis enim lobortis. Nam libero justo laoreet sit amet cursus sit. Ipsum dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. Cum sociis natoque penatibus et magnis dis. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Hac habitasse platea dictumst vestibulum rhoncus est. Nisi scelerisque eu ultrices vitae. Id aliquet risus feugiat in ante metus dictum at tempor. Elit eget gravida cum sociis.
Purus in mollis nunc sed id semper risus in hendrerit. Facilisis gravida neque convallis a. Duis tristique sollicitudin nibh sit amet commodo nulla. Non blandit massa enim nec dui nunc mattis enim ut. Blandit turpis cursus in hac habitasse. Ultrices neque ornare aenean euismod elementum nisi quis. Pellentesque pulvinar pellentesque habitant morbi. Aliquam sem fringilla ut morbi tincidunt augue. Sed libero enim sed faucibus turpis in. Purus sit amet luctus venenatis. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget nullam. Aliquam id diam maecenas ultricies. Interdum varius sit amet mattis vulputate enim. Ut placerat orci nulla pellentesque dignissim enim sit.
Quam pellentesque nec nam aliquam sem et tortor consequat id. Sit amet commodo nulla facilisi nullam vehicula ipsum a. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Dictum non consectetur a erat nam at lectus urna duis. Mollis nunc sed id semper risus. Commodo odio aenean sed adipiscing diam donec adipiscing tristique risus. Pretium vulputate sapien nec sagittis. Cum sociis natoque penatibus et. In ornare quam viverra orci sagittis eu volutpat. Quisque sagittis purus sit amet volutpat. Aliquet risus feugiat in ante metus dictum at. At auctor urna nunc id cursus metus aliquam. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Tellus molestie nunc non blandit massa enim nec dui nunc. Amet risus nullam eget felis eget nunc lobortis. Arcu dictum varius duis at consectetur lorem.
Arcu ac tortor dignissim convallis. Non pulvinar neque laoreet suspendisse interdum consectetur. Malesuada fames ac turpis egestas. Lectus nulla at volutpat diam ut venenatis tellus in metus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat. Justo laoreet sit amet cursus sit amet dictum sit. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Quam pellentesque nec nam aliquam sem et tortor. Varius sit amet mattis vulputate enim. Sit amet cursus sit amet dictum sit amet justo. Commodo quis imperdiet massa tincidunt. Est sit amet facilisis magna. Neque aliquam vestibulum morbi blandit cursus. Pharetra sit amet aliquam id diam. Elit ut aliquam purus sit.
`
